const items = [
  {
    id: 1,
    name: "Nike Air Force 1 '07 LV8",
    description: "Classic white Nike Air Force 1 sneakers in size 9",
    startingBid: "$80",
    categories: ["Fashion", "Shoes"],
    imageUrl: "https://via.placeholder.com/300x200",
    counter: 24,
    status: true,
  },
  {
    id: 2,
    name: "Apple AirPods Pro",
    description: "Brand new Apple AirPods Pro with noise cancellation",
    startingBid: "$150",
    categories: ["Electronics", "Audio"],
    imageUrl: "https://via.placeholder.com/300x200",
    counter: 48,
    status: true,
  },
  {
    id: 3,
    name: "Samsung Galaxy Watch",
    description: "Samsung Galaxy Watch in Midnight Black",
    startingBid: "$200",
    categories: ["Electronics", "Wearable Devices"],
    imageUrl: "https://via.placeholder.com/300x200",
    counter: 72,
    status: true,
  },
  {
    id: 4,
    name: "Levi's Trucker Jacket",
    description: "Levi's Trucker Jacket in Medium Wash",
    startingBid: "$60",
    categories: ["Fashion", "Jackets"],
    imageUrl: "https://via.placeholder.com/300x200",
    counter: 96,
    status: true,
  },
  {
    id: 5,
    name: "Sony PlayStation 5",
    description: "Brand new Sony PlayStation 5 with 1TB SSD",
    startingBid: "$500",
    categories: ["Electronics", "Gaming"],
    imageUrl: "https://via.placeholder.com/300x200",
    counter: 24,
    status: true,
  },
  {
    id: 6,
    name: "Canon EOS Rebel T7 DSLR Camera",
    description: "Brand new Canon EOS Rebel T7 DSLR Camera with 18-55mm lens",
    startingBid: "$400",
    categories: ["Electronics", "Cameras"],
    imageUrl: "https://via.placeholder.com/300x200",
    counter: 48,
    status: true,
  },
  {
    id: 7,
    name: "Bose QuietComfort 35 II Wireless Headphones",
    description:
      "Brand new Bose QuietComfort 35 II Wireless Headphones with noise cancellation",
    startingBid: "$250",
    categories: ["Electronics", "Audio"],
    imageUrl: "https://via.placeholder.com/300x200",
    counter: 24,
    status: true,
  },
  {
    id: 8,
    name: "Levi's 501 Original Fit Jeans",
    description: "Levi's 501 Original Fit Jeans in Dark Stonewash",
    startingBid: "$50",
    categories: ["Fashion", "Jeans"],
    imageUrl: "https://via.placeholder.com/300x200",
    counter: 72,
    status: true,
  },
  {
    id: 9,
    name: "Apple Watch Series 6",
    description: "Brand new Apple Watch Series 6 in Blue",
    startingBid: "$350",
    categories: ["Electronics", "Wearable Devices"],
    imageUrl: "https://via.placeholder.com/300x200",
    counter: 96,
    status: true,
  },
  {
    id: 10,
    name: "Adidas Ultraboost 21 Shoes",
    description: "Brand new Adidas Ultraboost 21 Shoes in size 10",
    startingBid: "$150",
    categories: ["Fashion", "Shoes"],
    imageUrl: "https://via.placeholder.com/300x200",
    counter: 24,
    status: true,
  },
  {
    id: 11,
    name: "Dell XPS 13 Laptop",
    description:
      "Brand new Dell XPS 13 Laptop with 11th Gen Intel Core i5 Processor",
    startingBid: "$1000",
    categories: ["Electronics", "Computers"],
    imageUrl: "https://via.placeholder.com/300x200",
    counter: 72,
    status: true,
  },
  {
    id: 12,
    name: "Samsung Galaxy S21 Ultra 5G",
    description: "Brand new Samsung Galaxy S21 Ultra 5G in Phantom Black",
    startingBid: "$1200",
    categories: ["Electronics", "Phones"],
    imageUrl: "https://via.placeholder.com/300x200",
    counter: 48,
    status: true,
  },
  {
    id: 13,
    name: "Champion Reverse Weave Hoodie",
    description: "Champion Reverse Weave Hoodie in Oxford Gray",
    startingBid: "$60",
    categories: ["Fashion", "Sweatshirts"],
    imageUrl: "https://via.placeholder.com/300x200",
    counter: 24,
    status: true,
  },
  {
    id: 14,
    name: "Fitbit Charge 5",
    description: "Brand new Fitbit Charge 5 with EDA Sensor and ECG App",
    startingBid: "$150",
    categories: ["Electronics", "Wearable Devices"],
    imageUrl: "https://via.placeholder.com/300x200",
    counter: 96,
    status: true,
  },
  {
    id: 15,
    name: "New Balance Fresh Foam 1080v11",
    description:
      "Brand new New Balance Fresh Foam 1080v11 Running Shoes in size 9",
    startingBid: "$120",
    categories: ["Fashion", "Shoes"],
    imageUrl: "https://via.placeholder.com/300x200",
    counter: 48,
    status: true,
  },
  {
    id: 16,
    name: "Amazon Echo (4th Gen)",
    description: "Brand new Amazon Echo (4th Gen) Smart Speaker with Alexa",
    startingBid: "$100",
    categories: ["Electronics", "Smart Home"],
    imageUrl: "https://via.placeholder.com/300x200",
    counter: 24,
    status: true,
  },
  {
    id: 17,
    name: "ASUS ROG Swift PG279QZ Gaming Monitor",
    description:
      "ASUS ROG Swift PG279QZ Gaming Monitor with WQHD (2560 x 1440) IPS Panel",
    startingBid: "$500",
    categories: ["Electronics", "Gaming"],
    imageUrl: "https://via.placeholder.com/300x200",
    counter: 72,
    status: true,
  },
  {
    id: 18,
    name: "Polo Ralph Lauren Classic Fit Oxford Shirt",
    description: "Polo Ralph Lauren Classic Fit Oxford Shirt in White",
    startingBid: "$80",
    categories: ["Fashion", "Shirts"],
    imageUrl: "https://via.placeholder.com/300x200",
    counter: 96,
    status: true,
  },
  {
    id: 19,
    name: "Fitbit Versa 3",
    description: "Brand new Fitbit Versa 3 Smartwatch with GPS",
    startingBid: "$200",
    categories: ["Electronics", "Wearable Devices"],
    imageUrl: "https://via.placeholder.com/300x200",
    counter: 48,
    status: true,
  },
  {
    id: 20,
    name: "Nike Flex Stride 2-in-1 Shorts",
    description: "Nike Flex Stride 2-in-1 Running Shorts in size M",
    startingBid: "$50",
    categories: ["Fashion", "Athletic Wear"],
    imageUrl: "https://via.placeholder.com/300x200",
    counter: 24,
    status: true,
  },
];

export default items;
